version: 1.0.{build}
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  publish_wap: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: Environment
  name: SiteMusica
  artifact: SiteMusica.zip
  on:
      branch: master
